### ISSUE TITLE
Remove PANO_ prefix

### ISSUE THREAD

**Issue by Sanookmakmak** [R0Wi/Nextcloud-PhotoSphereViewer#4]
Use exiftool instead to recognize a panorama.

Read the value "XMP/ProjectionType", if it is "equirectangular" then display use the panoramaviewer.

Like QuickPic for Android is doing: https://play.google.com/store/apps/details?id=com.photography.gallery

**Comment by R0Wi** [comment]
The photosphere-viewer.js-Library internally already uses some kind of "check-mechanism", if the current displayed image has the photosphere-metadata. So it would be nice to use this functionallity to implement a clientside check. The problem is, that currently this functionallity isn't exposed. So i'd have to extract this into a kind of function where the caller can use it.

Also to realize this, a full integration into the gallery app must be provided which is a separate task for the future.

**Comment by R0Wi** [comment]
Moved to [https://github.com/nextcloud/files_photospheres/issues/4]()
